---
# Install Packer
# Based on <https://developer.hashicorp.com/packer/tutorials/docker-get-started/get-started-install-cli>
# and <https://www.terraform.io/docs/cli/install/apt.html>
# Updated for apt-key deprecation

- name: Add the Hashicorp package repository
  block:
    - name: Download the Hashicorp package repository signing key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
        mode: '0644'
        force: true

    - name: Add the Hashicorp package repository to /etc/apt/sources.list.d
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ansible_distribution_release}} main"
        filename: hashicorp
        state: present

- name: Install Packer
  apt:
    name: "packer"
    update_cache: yes
...
